name: Release 

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version for the release'
        required: true
        default: '1.0.0'
        type: string

jobs:
  release:
    runs-on: ubuntu-22.04
    env:
      CICD_TOKEN: ${{ secrets.CICD_TOKEN }}
      RELEASE: ${{ inputs.version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2
 
      - name: Run release manager 
        run: module.sh
          
      - name: Create Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          token: ${{ secrets.CICD_TOKEN }}
          tag_name: v${{ env.RELEASE }}
          name: "v${{ env.RELEASE }}"

      - name: Unset cicd token 
        run: unset CICD_TOKEN
